# cancel_reservations_job:
#   cron: "*/5 * * * *"
#   class: "CancelReservationsJob"
#   description: "Cancel rreservatioons that were not paid 30 before screening"
#   name: "Cancel Reservations"
#   queue: "default"